/**
 * Report — render the analysis into human-reviewable deliverables.
 *
 * Writes to an output folder:
 *   AUDIT_REPORT.md         master evidence report (the auditor reads/edits this)
 *   audit-result.json       full structured result (machine-readable)
 *   documents/<name>.md     one annotated file per document (sorted, highlighted)
 *
 * Every positive line is a verbatim quote of the client's own text with a line
 * reference. Every gap is stated as a plain "not found". Nothing is invented.
 */
import { mkdir, writeFile, rm } from 'node:fs/promises';
import { join } from 'node:path';

const WEIGHT_TAG = { critical: 'CRITICAL', expected: 'expected' };
const MAX_LIST_ITEMS = 4;

function safeName(rel) {
  return rel.replace(/[\/\\]+/g, '__').replace(/[^\w.\- ]+/g, '_');
}

function pct(n, d) {
  return d === 0 ? '—' : `${Math.round((n / d) * 100)}%`;
}

function joinLabels(items, limit = MAX_LIST_ITEMS) {
  const list = items.filter(Boolean);
  if (!list.length) return 'none';
  const shown = list.slice(0, limit).map((s) => esc(s));
  if (list.length > limit) shown.push(`and ${list.length - limit} more`);
  return shown.join('; ');
}

function topFilesFromSignals(signals, limit = 2) {
  const counts = new Map();
  for (const s of signals) {
    for (const loc of s.locations ?? []) {
      if (!loc.file) continue;
      counts.set(loc.file, (counts.get(loc.file) ?? 0) + 1);
    }
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, limit)
    .map(([file, count]) => `${file}${count > 1 ? ` (${count})` : ''}`);
}

function areaCriticalMissing(a) {
  return a.signals.filter((s) => s.weight === 'critical' && !s.met).map((s) => s.label);
}

function areaExpectedMissing(a) {
  return a.signals.filter((s) => s.weight !== 'critical' && !s.met).map((s) => s.label);
}

function areaSummary(a) {
  if (a.docCount === 0) {
    return `No document was matched to Area ${a.area}.`;
  }
  const criticalMissing = areaCriticalMissing(a);
  const expectedMissing = areaExpectedMissing(a);
  let text = `This area has ${a.criticalMet}/${a.criticalTotal} critical signals met and ${a.metCount}/${a.totalCount} signals met overall.`;
  if (criticalMissing.length) {
    text += ` Missing critical items: ${joinLabels(criticalMissing)}.`;
  } else if (expectedMissing.length) {
    text += ` The remaining gaps are expected items: ${joinLabels(expectedMissing)}.`;
  } else {
    text += ' All listed signals are evidenced.';
  }
  const sourceFiles = topFilesFromSignals(a.signals.filter((s) => s.met), 2);
  if (sourceFiles.length) {
    text += ` Main source documents: ${sourceFiles.join('; ')}.`;
  }
  return text;
}

function documentSummary(d) {
  if (!d.readable) {
    return 'This document could not be read as text, so its contents were not assessed.';
  }
  const met = d.signals.filter((s) => s.found);
  const criticalMet = met.filter((s) => s.weight === 'critical').length;
  const totalCritical = d.signals.filter((s) => s.weight === 'critical').length;
  const gaps = d.signals.filter((s) => !s.found);
  const criticalGaps = gaps.filter((s) => s.weight === 'critical').map((s) => s.label);
  const expectedGaps = gaps.filter((s) => s.weight !== 'critical').map((s) => s.label);
  let text = `This document is classified as ${d.classification.ref ?? 'an unmatched file'}${d.classification.title ? ` (${d.classification.title})` : ''}. `;
  if (d.classification.areaName) text += `Area: ${d.classification.area} ${d.classification.areaName}. `;
  text += `Signal coverage is ${criticalMet}/${totalCritical} critical and ${met.length}/${d.signals.length} overall. `;
  if (criticalGaps.length) {
    text += `Critical gaps remain: ${joinLabels(criticalGaps)}.`;
  } else if (expectedGaps.length) {
    text += `Remaining gaps are expected items: ${joinLabels(expectedGaps)}.`;
  } else {
    text += 'All listed signals for this document are evidenced.';
  }
  if (d.redFlags.length) {
    text += ` ${d.redFlags.length} red flag${d.redFlags.length === 1 ? '' : 's'} detected.`;
  }
  return text;
}

/* -------------------------------------------------------------------------- */
/* Master report                                                               */
/* -------------------------------------------------------------------------- */

function renderMaster(result) {
  const t = result.totals;
  const L = [];
  const p = (s = '') => L.push(s);

  p('# CQC Policy Evidence Report');
  p('');
  p('> Generated by the BizCompliance Policy Evidence Reader. Every item below is');
  p('> either a **verbatim quote** from a supplied document (with its line number)');
  p('> or a plain statement that specific evidence **was not found**. Nothing in');
  p('> this report is generated, inferred or assumed. **Human review required** before issue.');
  p('');
  p(`- **Generated:** ${result.generatedAt}`);
  p(`- **Source:** \`${result.root}\``);
  p('');

  p('## 1. At a glance');
  p('');
  p('| Measure | Value |');
  p('|---|---|');
  p(`| Files received | ${t.filesReceived} |`);
  p(`| Readable / assessed | ${t.readable} |`);
  p(`| Could not be read (need human review) | ${t.unreadable} |`);
  p(`| Library documents supplied | **${t.manifestSupplied} of ${t.manifestTotal}** (${pct(t.manifestSupplied, t.manifestTotal)}) |`);
  p(`| Legally-required documents missing | **${t.missingLegal}** |`);
  p(`| CQC-expected documents missing | ${t.missingCqc} |`);
  p(`| Critical evidence signals met | **${t.criticalSignalsMet} of ${t.criticalSignalsTotal}** (${pct(t.criticalSignalsMet, t.criticalSignalsTotal)}) |`);
  p(`| Critical red flags (placeholders/template text) | ${t.criticalRedFlags} |`);
  p(`| Documents past their review date | ${t.overdueDocs} |`);
  p('');

  p('## 2. Executive summary');
  p('');
  p(`The supplied set contains ${t.filesReceived} files. ${t.manifestSupplied} of ${t.manifestTotal} library documents were supplied and ${t.missingLegal} legally-required documents are missing.`);
  if (t.criticalSignalsTotal > 0) {
    p(`The analysis met ${t.criticalSignalsMet} of ${t.criticalSignalsTotal} critical evidence signals.`);
  }
  if (t.criticalRedFlags > 0) {
    p(`Template or legacy-language issues were detected in ${t.criticalRedFlags} line${t.criticalRedFlags === 1 ? '' : 's'}.`);
  } else {
    p('No critical template or legacy-language red flags were detected.');
  }
  if (t.overdueDocs > 0) {
    p(`${t.overdueDocs} document${t.overdueDocs === 1 ? '' : 's'} is past its review date.`);
  } else {
    p('No supplied document is past its stated review date.');
  }
  if (result.unreadable.length > 0) {
    p(`${result.unreadable.length} file${result.unreadable.length === 1 ? '' : 's'} could not be read and must be checked manually.`);
  } else {
    p('All supplied files were readable.');
  }
  const criticalAreas = result.areaRollup.filter((a) => a.criticalGaps.length > 0);
  if (criticalAreas.length) {
    p(`Critical gaps remain in ${criticalAreas.length} compliance area${criticalAreas.length === 1 ? '' : 's'}: ${criticalAreas.map((a) => `Area ${a.area} ${a.areaName}`).join('; ')}.`);
  } else {
    p('No compliance area has an unmet critical signal.');
  }
  p('');

  p('## 3. Priority findings');
  p('');
  const missingLegal = result.coverage.filter((c) => !c.supplied && c.requirement === 'legal');
  const criticalGaps = result.areaRollup.flatMap((a) =>
    a.signals.filter((s) => !s.met && s.weight === 'critical').map((s) => ({
      area: a.area,
      areaName: a.areaName,
      label: s.label,
    })),
  );
  if (missingLegal.length) {
    p('### Missing legally-required documents');
    p('');
    for (const c of missingLegal) {
      p(`- ${c.ref} · ${esc(c.title)} · Area ${c.area} ${esc(areaName(result, c.area))}`);
    }
    p('');
  } else {
    p('### Missing legally-required documents');
    p('');
    p('None.');
    p('');
  }
  if (criticalGaps.length) {
    p('### Critical evidence gaps');
    p('');
    for (const gap of criticalGaps) {
      p(`- Area ${gap.area} ${esc(gap.areaName)} · ${esc(gap.label)}`);
    }
    p('');
  }
  if (t.criticalRedFlags > 0) {
    p('### Red flags');
    p('');
    p(`Critical template or legacy-language issues were found in ${t.criticalRedFlags} line${t.criticalRedFlags === 1 ? '' : 's'}.`);
    p('');
  }
  if (t.overdueDocs > 0) {
    p('### Overdue reviews');
    p('');
    for (const d of result.perDoc.filter((d) => d.review && d.review.status === 'overdue')) {
      p(`- ${esc(d.file)} · ${d.review.date}`);
    }
    p('');
  }
  if (result.unreadable.length) {
    p('### Files requiring manual review');
    p('');
    for (const u of result.unreadable) {
      p(`- ${esc(u.file)} · ${esc(u.warning)}`);
    }
    p('');
  }

  // Per-area evidence.
  p('## 4. Evidence by compliance area');
  p('');
  for (const a of result.areaRollup) {
    const flag = a.criticalGaps.length > 0 ? '🔴' : a.metCount < a.totalCount ? '🟠' : '🟢';
    p(`### ${flag} Area ${a.area} — ${esc(a.areaName)}`);
    p('');
    p(areaSummary(a));
    p('');
    p(`Documents assessed in this area: **${a.docCount}** · Critical signals met: **${a.criticalMet}/${a.criticalTotal}** · All signals: ${a.metCount}/${a.totalCount}`);
    p('');
    const met = a.signals.filter((s) => s.met);
    const gaps = a.signals.filter((s) => !s.met);
    if (met.length) {
      p('**Evidence found:**');
      p('');
      for (const s of met) {
        const first = s.locations[0];
        const cite = first ? ` — _${esc(first.file)}_ line ${first.line}: “${esc(first.quote)}”` : '';
        p(`- ✓ ${esc(s.label)}${cite}`);
      }
      p('');
    }
    if (gaps.length) {
      p('**Not found in the documents supplied for this area:**');
      p('');
      for (const s of gaps) {
        p(`- ✗ ${esc(s.label)}${s.weight === 'critical' ? ' **(critical)**' : ''}`);
      }
      p('');
    }
    if (a.docCount === 0) {
      p('_No document was matched to this area. Any evidence above would come from documents filed elsewhere; confirm coverage._');
      p('');
    }
  }

  // Extended expectations.
  p('## 5. Wider evidence (beyond the core library)');
  p('');
  p('_Additional artefacts inspectors, commissioners and insurers commonly ask for._');
  p('');
  p('| Evidence | Present in supplied documents? | Where |');
  p('|---|---|---|');
  for (const e of result.extended) {
    const loc = e.supplied && e.locations[0] ? `${esc(e.locations[0].file)} L${e.locations[0].line}` : '—';
    p(`| ${esc(e.label)} | ${e.supplied ? '✓ Yes' : '✗ Not found'} | ${loc} |`);
  }
  p('');

  // Red flags.
  const flags = [];
  for (const d of result.perDoc) {
    for (const f of d.redFlags) flags.push({ file: d.file, ...f });
  }
  p('## 6. Red flags found in document text');
  p('');
  if (!flags.length) {
    p('None found — no unfilled placeholders, template artifacts or outdated-regime language detected. ✓');
  } else {
    p('_Each is a verbatim quote of the offending line._');
    p('');
    p('| Document | Line | Issue | Text |');
    p('|---|---|---|---|');
    for (const f of flags.slice(0, 400)) {
      p(`| ${esc(f.file)} | ${f.line} | ${esc(f.label)}${f.severity === 'critical' ? ' (critical)' : ''} | “${esc(f.quote)}” |`);
    }
  }
  p('');

  // Overdue / review dates.
  const reviews = result.perDoc.filter((d) => d.review);
  p('## 7. Document review dates');
  p('');
  if (!reviews.length) {
    p('No explicit review dates were detected in the supplied documents.');
  } else {
    p('| Document | Stated review date | Status | Line |');
    p('|---|---|---|---|');
    for (const d of reviews) {
      const badge = d.review.status === 'overdue' ? '🔴 OVERDUE' : d.review.status === 'due_soon' ? '🟠 due soon' : '🟢 current';
      p(`| ${esc(d.file)} | ${d.review.date} | ${badge} | ${d.review.line} |`);
    }
  }
  p('');

  // Attention lists.
  if (result.unreadable.length) {
    p('## 8. Files that could not be read (must be reviewed by a human)');
    p('');
    p('| File | Type | Reason |');
    p('|---|---|---|');
    for (const u of result.unreadable) p(`| ${esc(u.file)} | ${u.ext || '—'} | ${esc(u.warning)} |`);
    p('');
  }
  if (result.unmatched.length) {
    p('## 9. Files needing manual classification');
    p('');
    p('| File | Confidence | Note |');
    p('|---|---|---|');
    for (const u of result.unmatched) p(`| ${esc(u.file)} | ${u.confidence} | ${esc(u.reason)} |`);
    p('');
  }

  p('---');
  p('');
  p('_This report identifies the presence or absence of evidence in the documents supplied. It does not certify compliance, and the registered provider and registered manager remain accountable for compliance with the law. All findings must be confirmed by the reviewing auditor before this report is issued to a client._');
  p('');
  return L.join('\n');
}

/* -------------------------------------------------------------------------- */
/* Per-document annotated file                                                 */
/* -------------------------------------------------------------------------- */

function renderDoc(d) {
  const L = [];
  const p = (s = '') => L.push(s);
  const c = d.classification;

  p(`# ${esc(d.fileName)}`);
  p('');
  if (c.ref) {
    p(`- **Identified as:** ${c.ref} — ${esc(c.title)}  (area ${c.area} · ${esc(c.areaName)})`);
    p(`- **Requirement level:** ${c.requirement ?? '—'}`);
    if (c.basis) p(`- **Regulatory basis:** ${esc(c.basis)}`);
  } else if (c.area) {
    p(`- **Best-guess area:** ${c.area} · ${esc(c.areaName)}`);
  } else {
    p('- **Classification:** could not be determined automatically.');
  }
  p(`- **Match confidence:** ${c.confidence} — ${esc(c.reason)}`);
  p(`- **Lines read:** ${d.lineCount}`);
  if (d.warning) p(`- ⚠️ **Note:** ${esc(d.warning)}`);
  p('');

  if (!d.readable) {
    p('> This document could not be read as text, so its contents were not assessed. Review it manually.');
    p('');
    return L.join('\n');
  }

  p('## Document summary');
  p('');
  p(documentSummary(d));
  p('');

  const met = d.signals.filter((s) => s.found);
  const gaps = d.signals.filter((s) => !s.found);

  p('## Evidence found in this document');
  p('');
  if (!met.length) {
    p('_No area evidence signals matched. Confirm this is the right document for its area._');
  } else {
    for (const s of met) {
      p(`- ✓ **${esc(s.label)}**`);
      for (const cite of s.citations) {
        p(`    - line ${cite.line}: “${esc(cite.quote)}”`);
      }
    }
  }
  p('');

  if (gaps.length) {
    p('## Expected evidence NOT found in this document');
    p('');
    for (const s of gaps) {
      p(`- ✗ ${esc(s.label)}${s.weight === 'critical' ? ' **(critical)**' : ''}`);
    }
    p('');
  }

  p('## Document control');
  p('');
  for (const dc of d.docControl) {
    const cite = dc.found && dc.citation ? ` — line ${dc.citation.line}: “${esc(dc.citation.quote)}”` : '';
    p(`- ${dc.found ? '✓' : '✗'} ${esc(dc.label)}${cite}`);
  }
  p('');

  if (d.redFlags.length) {
    p('## Red flags');
    p('');
    for (const f of d.redFlags) {
      p(`- ⚠️ ${esc(f.label)}${f.severity === 'critical' ? ' (critical)' : ''} — line ${f.line}: “${esc(f.quote)}”`);
    }
    p('');
  }

  if (d.review) {
    p('## Review date');
    p('');
    p(`- Stated: **${d.review.date}** (${d.review.status}) — line ${d.review.line}: “${esc(d.review.quote)}”`);
    p('');
  }

  return L.join('\n');
}

function esc(s) {
  return String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
function areaName(result, area) {
  const a = result.areaRollup.find((x) => x.area === area);
  return a ? a.areaName : '';
}

/* -------------------------------------------------------------------------- */
/* Writer                                                                      */
/* -------------------------------------------------------------------------- */

export async function writeReport(result, outDir) {
  await rm(outDir, { recursive: true, force: true });
  await mkdir(join(outDir, 'documents'), { recursive: true });

  await writeFile(join(outDir, 'AUDIT_REPORT.md'), renderMaster(result), 'utf8');
  await writeFile(join(outDir, 'audit-result.json'), JSON.stringify(result, null, 2), 'utf8');

  for (const d of result.perDoc) {
    await writeFile(join(outDir, 'documents', `${safeName(d.file)}.md`), renderDoc(d), 'utf8');
  }

  return {
    master: join(outDir, 'AUDIT_REPORT.md'),
    json: join(outDir, 'audit-result.json'),
    docsDir: join(outDir, 'documents'),
  };
}

export { renderMaster, renderDoc };
