-- ============================================================================
-- BizCompliance — Migration 0002: static reference data
-- 18 compliance areas (CQC Manual Audit Checklist, build 20 June 2026)
-- 68 SAF interview questions (CQC SAF Interview & Evidence Sheet, same build)
-- ============================================================================

insert into public.library_areas (code, name, regulation_title, regulation_summary, sort) values
('01', 'Registration & Statement of Purpose', 'Reg 12 (Registration Regs 2009) — Statement of purpose', 'The registered provider must provide the Commission with a statement of purpose containing the matters listed in Schedule 3 and keep it under review. (CQC (Registration) Regulations 2009 — separate instrument from the 2014 Regulated Activities Regulations.)', 1),
('02', 'Safeguarding Adults', 'Regulation 13 — Safeguarding service users from abuse and improper treatment', 'Service users must be protected from abuse and improper treatment. Systems must prevent abuse and investigate immediately upon any allegation or evidence of abuse. No deprivation of liberty without lawful authority. (HSCA 2008 (RA) Regs 2014.)', 2),
('03', 'Consent & Mental Capacity', 'Regulation 11 — Need for consent', 'Care and treatment must only be provided with the consent of the relevant person. Where a service user 16+ lacks capacity, the registered person must act in accordance with the Mental Capacity Act 2005.', 3),
('04', 'Safe Care & Risk Management', 'Regulation 12 — Safe care and treatment', 'Care and treatment must be provided in a safe way: assessing risks, mitigating them, ensuring competent staff, safe premises and equipment, proper and safe management of medicines, and infection control.', 4),
('05', 'Lone Working & Staff Safety', 'Reg 3, MHSWR 1999 (+ Reg 12/18) — Risk assessment for staff safety', 'Employers must make a suitable and sufficient assessment of the risks to the health and safety of employees at work. Links to Reg 12 (safe care) and Reg 18 (competent staff deployment).', 5),
('06', 'Medicines Management', 'Regulation 12(2)(g) — Proper and safe management of medicines', 'Sufficient quantities of medicines and equipment to ensure safety; proper and safe management of medicines. NICE NG67 and Misuse of Drugs Regs 2001 are the operational standards.', 6),
('07', 'Person-Centred Care & Care Planning', 'Regulation 9 — Person-centred care', 'Care and treatment must be appropriate, meet needs and reflect preferences, including collaborative needs assessment and care design. Nutrition/hydration documents engage Reg 14.', 7),
('08', 'Complaints & Feedback', 'Regulation 16 — Receiving and acting on complaints', 'Any complaint must be investigated with necessary and proportionate action taken. An accessible system for identifying, receiving, recording, handling and responding to complaints must operate effectively.', 8),
('09', 'Duty of Candour', 'Regulation 20 — Duty of candour', 'Registered persons must act openly and transparently. After a notifiable safety incident: notify the relevant person, provide a true account, apologise, and keep a secure written record. Reg 20(9) threshold applies to non-health-service bodies.', 9),
('10', 'Governance, QA & Records', 'Regulation 17 — Good governance', 'Systems must assess, monitor and improve quality and safety, assess and mitigate risks, and maintain securely an accurate, complete and contemporaneous record for each service user.', 10),
('11', 'Staffing, Training & Supervision', 'Regulation 18 — Staffing', 'Sufficient numbers of suitably qualified, competent, skilled and experienced persons must be deployed, with appropriate support, training, professional development, supervision and appraisal.', 11),
('12', 'Safe Recruitment & DBS', 'Regulation 19 — Fit and proper persons employed', 'Persons employed must be of good character with necessary qualifications, competence, skills and experience. Recruitment procedures must operate effectively with Schedule 3 information available for each person.', 12),
('13', 'Data Protection & Confidentiality', 'UK GDPR / DPA 2018 (+ Reg 17) — Lawful processing of personal data', 'Personal data must be processed lawfully, fairly and transparently; health data is special-category data requiring an Article 9 condition. ROPA required under Article 30. ICO breach reporting within 72 hours where the threshold is met.', 13),
('14', 'Health & Safety (office & community)', 'HSWA 1974 s.2 (+ subordinate regs) — Health, safety and welfare at work', 'Employers must ensure, so far as reasonably practicable, the health, safety and welfare at work of employees; written H&S policy required with 5+ employees. Fire (RRO 2005), COSHH 2002 and RIDDOR 2013 are subordinate duties.', 14),
('15', 'Infection Prevention & Control', 'Regulation 12(2)(h) — Preventing and controlling infection', 'Assessing the risk of, and preventing, detecting and controlling the spread of infections, including those that are health care associated. The IPC Code of Practice (HSCA 2008 s.21) is the detailed standard.', 15),
('16', 'Notifications (CQC statutory)', 'Regs 16–18 (Registration Regs 2009) — Notification of deaths, injuries and other incidents', 'Registered persons must notify the Commission of specified events (death of a service user, serious injuries, deprivation of liberty outcomes, certain other incidents) without delay.', 16),
('17', 'Business Continuity & Emergency Planning', 'Regulation 17 — Good governance (continuity)', 'Business continuity is assessed as part of risk mitigation under good governance; assess, monitor and mitigate risks to health, safety and welfare arising from the regulated activity.', 17),
('18', 'Dignity, Equality & Service-User Rights', 'Regulation 10 — Dignity and respect', 'Service users must be treated with dignity and respect, including privacy, autonomy, independence, community involvement, and due regard to protected characteristics (Equality Act 2010 s.149(7)).', 18)
on conflict (code) do update set
  name = excluded.name,
  regulation_title = excluded.regulation_title,
  regulation_summary = excluded.regulation_summary,
  sort = excluded.sort;

-- ----------------------------------------------------------------------------
-- SAF interview questions (68) — Y/Partial/No/N-A, priority = rapid triage ★
-- ----------------------------------------------------------------------------
insert into public.saf_questions (id, domain, statement_no, statement, question, evidence_hint, priority) values
-- SAFE (16 questions)
(1, 'safe', 1, 'Learning culture', 'Is there a documented whistleblowing policy that 100% of staff have signed an acknowledgment of within the last 12 months?', 'Whistleblowing policy document, signed staff acknowledgment log.', false),
(2, 'safe', 1, 'Learning culture', 'Are all reported safety incidents reviewed in a monthly management meeting with documented action plans and assigned owners?', 'Monthly management meeting minutes, action plan tracker.', false),
(3, 'safe', 2, 'Safe systems, pathways, and transitions', 'Is a standardized handover checklist completed and signed by both the outgoing and incoming staff member at every shift change?', 'Blank and completed standardized handover checklists.', false),
(4, 'safe', 2, 'Safe systems, pathways, and transitions', 'Are hospital discharge summaries reviewed by a nurse within 2 hours, and care plans updated within 24 hours of a resident''s return?', 'Hospital discharge summaries with timestamps, updated care plans.', false),
(5, 'safe', 3, 'Safeguarding', 'Have all staff completed up-to-date Level 2 Safeguarding Adults training within the last 12 months with passed assessments?', 'Training matrix, safeguarding certificates with pass marks.', true),
(6, 'safe', 3, 'Safeguarding', 'Is the local authority safeguarding contact number displayed on the back of every staff ID badge and in the staff room?', 'Visual check of staff ID badges and staff room notice boards.', false),
(7, 'safe', 4, 'Involving people to manage risks', 'Are positive risk-taking assessments co-produced with the service user and their family, and signed off by the Registered Manager?', 'Signed positive risk-taking assessments in care plans.', false),
(8, 'safe', 4, 'Involving people to manage risks', 'Are dynamic risk assessments updated within 24 hours of any significant change in a service user''s mobility or cognitive state?', 'Dynamic risk assessments with 24-hour update timestamps.', true),
(9, 'safe', 5, 'Safe environments', 'Are fire safety checks (e.g., fire doors, emergency lighting, call bell systems) logged daily by the on-site maintenance lead?', 'Daily fire safety check logs signed by maintenance lead.', false),
(10, 'safe', 5, 'Safe environments', 'Are ligature risk assessments completed and signed off quarterly for all bedrooms and bathrooms of service users identified as high-risk?', 'Quarterly ligature risk assessment reports for high-risk rooms.', false),
(11, 'safe', 6, 'Safe and effective staffing', 'Does the agency fill 100% of unplanned shift vacancies within 2 hours of the cancellation using a pre-vetted bank staff list?', 'Shift vacancy logs, agency staff vetting and induction records.', true),
(12, 'safe', 6, 'Safe and effective staffing', 'Are agency staff briefed using a standardized agency induction checklist that is signed by the nurse in charge before they provide care?', 'Signed agency induction checklists by Nurse in Charge.', false),
(13, 'safe', 7, 'Infection prevention and control', 'Are weekly IPC audits conducted using the National IPC manual tool, with a scored action plan implemented for any score below 85%?', 'Weekly IPC audit reports with action plans for scores <85%.', false),
(14, 'safe', 7, 'Infection prevention and control', 'Is the PPE stock level checked every Friday by the designated IPC lead, with a reorder triggered if stock falls below a 2-week supply?', 'Weekly PPE stock check logs and reorder receipts.', false),
(15, 'safe', 8, 'Medicines optimisation', 'Are MAR charts audited weekly by the Registered Manager with discrepancies signed off and actioned within 24 hours?', 'Weekly MAR chart audit logs signed by RM, discrepancy action logs.', true),
(16, 'safe', 8, 'Medicines optimisation', 'Are controlled drugs reconciled at every handover with two staff members co-signing the controlled drug book?', 'Controlled drug book with dual signatures at every handover.', true),
-- EFFECTIVE (12 questions)
(17, 'effective', 9, 'Assessing needs', 'Are comprehensive needs assessments completed within 48 hours of admission and reviewed formally every 3 months or upon significant change?', 'Completed needs assessments dated within 48h of admission.', true),
(18, 'effective', 9, 'Assessing needs', 'Do all care plans include a specific, documented communication profile detailing the service user''s preferred methods of expressing pain or distress?', 'Care plans containing specific communication profiles.', false),
(19, 'effective', 10, 'Delivering evidence-based care and treatment', 'Are pressure ulcer risk assessments (e.g., Waterlow) completed within 4 hours of admission and reviewed weekly with documented repositioning charts?', 'Waterlow assessments within 4h of admission, weekly repositioning charts.', false),
(20, 'effective', 10, 'Delivering evidence-based care and treatment', 'Is malnutrition screening (e.g., MUST) conducted weekly for all residents, with automatic dietitian referrals triggered for scores of 2 or higher?', 'Weekly MUST screening logs, dietitian referral letters for scores >=2.', false),
(21, 'effective', 11, 'How staff and teams work together', 'Are multi-disciplinary team (MDT) meetings held monthly with minutes shared to all relevant staff and external health professionals within 48 hours?', 'Monthly MDT meeting minutes, distribution logs to external pros.', false),
(22, 'effective', 11, 'How staff and teams work together', 'Is there a secure, GDPR-compliant digital system in place for sharing care plans and incident reports with community nurses and GPs in real-time?', 'GDPR-compliant digital system audit logs and access permissions.', false),
(23, 'effective', 12, 'Supporting people to live healthier lives', 'Are annual health action plans completed for all service users with a learning disability, including documented checks for reasonable adjustments?', 'Annual health action plans with reasonable adjustments documented.', false),
(24, 'effective', 12, 'Supporting people to live healthier lives', 'Is a weekly menu planned by a qualified dietitian and displayed in the dining area, with specific texture-modified diets clearly color-coded?', 'Weekly dietitian-planned menus, color-coded texture diet lists.', false),
(25, 'effective', 13, 'Monitoring and improving outcomes', 'Are service user weight and fluid intake charts audited monthly by the Nurse in Charge to identify unintended weight loss trends?', 'Monthly weight/fluid intake audit logs by Nurse in Charge.', false),
(26, 'effective', 13, 'Monitoring and improving outcomes', 'Is a quarterly patient outcome survey distributed to service users/relatives, with results analyzed and presented at the next governance meeting?', 'Quarterly patient outcome surveys, governance meeting minutes.', false),
(27, 'effective', 14, 'Consent to care and treatment', 'Are Mental Capacity Assessments (MCAs) documented and filed within the service user''s record prior to any new care intervention?', 'Mental Capacity Assessments (MCAs) filed prior to interventions.', true),
(28, 'effective', 14, 'Consent to care and treatment', 'Are Best Interests Decisions recorded with evidence of consulting at least two relevant consultees (e.g., family, advocate) before implementation?', 'Best Interests Decision records with two consultee signatures.', false),
-- CARING (10 questions)
(29, 'caring', 15, 'Kindness, compassion and dignity', 'Are knock-and-wait protocols strictly followed before entering any service user''s bedroom or bathroom to ensure privacy?', 'Observation of knock-and-wait protocols during care delivery.', false),
(30, 'caring', 15, 'Kindness, compassion and dignity', 'Are personal care tasks performed with doors and curtains fully closed, and service users covered with towels immediately after washing?', 'Observation of personal care tasks, privacy protocols in place.', true),
(31, 'caring', 16, 'Treating people as individuals', 'Does every service user''s bedroom door display a personalized, recognizable symbol or photo (e.g., Names at Doors) to support those with dementia?', 'Visual check of bedroom doors for personalized symbols/photos.', false),
(32, 'caring', 16, 'Treating people as individuals', 'Are life story books created for 100% of service users with dementia, detailing their past occupations, hobbies, and preferences?', 'Life story books present in 100% of dementia care files.', false),
(33, 'caring', 17, 'Independence, choice and control', 'Are service users given a choice of breakfast time, meal options, and wake-up times, with their choices documented in their daily care plan?', 'Daily care plans documenting user choices for meals/wake times.', false),
(34, 'caring', 17, 'Independence, choice and control', 'Is there a documented process to support service users to manage their own finances and medications if they have the capacity to do so?', 'Documented processes for user-managed finances/medications.', false),
(35, 'caring', 18, 'Responding to people''s immediate needs', 'Are call bells answered within 3 minutes, with the response time logged on the shift handover sheet?', 'Call bell response logs showing <3 min response times.', false),
(36, 'caring', 18, 'Responding to people''s immediate needs', 'Are pain management interventions reviewed and documented within 30 minutes of administration to assess effectiveness?', 'Pain management records showing 30-min post-admin reviews.', false),
(37, 'caring', 19, 'Workforce wellbeing and enablement', 'Are monthly 1-on-1 supervision sessions held with all staff, with a signed agenda and action points recorded?', 'Monthly 1-on-1 supervision records with signed agendas.', false),
(38, 'caring', 19, 'Workforce wellbeing and enablement', 'Is there a designated, private quiet room available for staff breaks, equipped with seating, a microwave, and a fridge?', 'Visual check of designated staff quiet room and facilities.', false),
-- RESPONSIVE (14 questions)
(39, 'responsive', 20, 'Person centred care', 'Are end-of-life care plans created and shared with the ambulance service and out-of-hours GP within 24 hours of a resident entering the last days of life?', 'End-of-life care plans shared with ambulance/OOH within 24h.', false),
(40, 'responsive', 20, 'Person centred care', 'Are care plan reviews conducted with the service user present (or their advocate), with their verbal feedback documented in the notes?', 'Care plan review notes documenting user/advocate verbal feedback.', true),
(41, 'responsive', 21, 'Care provision, integrity, and continuity', 'Are care visits for domiciliary care staff scheduled with a minimum 15-minute buffer for travel time to prevent rushed care?', 'Domiciliary care shift rotas showing 15-min travel buffers.', false),
(42, 'responsive', 21, 'Care provision, integrity, and continuity', 'Is there a documented contingency plan for IT system failures that ensures paper-based care records can be maintained without interruption?', 'Documented IT failure contingency plan and paper record samples.', false),
(43, 'responsive', 22, 'Providing information', 'Is the service user handbook available in large print, easy read, and at least three community languages relevant to the local demographic?', 'Service user handbooks in large print, easy read, and 3 languages.', false),
(44, 'responsive', 22, 'Providing information', 'Are all service users provided with a clear, written breakdown of their weekly fees and any potential top-up costs upon admission?', 'Fee breakdown documents provided to users at admission.', false),
(45, 'responsive', 23, 'Listening to and involving people', 'Is a service user/relative satisfaction survey conducted quarterly, with a 100% response rate to any formal complaints within 28 days?', 'Quarterly satisfaction surveys, complaint response logs (<28 days).', false),
(46, 'responsive', 23, 'Listening to and involving people', 'Are the minutes from the monthly service user meeting displayed on the main notice board within 48 hours of the meeting?', 'Service user meeting minutes displayed on notice board within 48h.', false),
(47, 'responsive', 24, 'Equity in access', 'Is the building entrance wheelchair accessible with an automated door and a functioning, height-adjusted reception desk?', 'Visual check of automated doors and height-adjusted reception.', false),
(48, 'responsive', 24, 'Equity in access', 'Are interpreter services booked at least 48 hours in advance for all MDT meetings involving service users with English as a second language?', 'Interpreter booking logs for MDT meetings (48h advance).', false),
(49, 'responsive', 25, 'Equity in experiences and outcomes', 'Is data on patient outcomes stratified by protected characteristics (e.g., ethnicity, gender) to identify and address any disparities in care quality?', 'Stratified patient outcome data reports by protected characteristics.', false),
(50, 'responsive', 25, 'Equity in experiences and outcomes', 'Are reasonable adjustments documented and implemented for all service users with sensory impairments (e.g., flashing fire alarms for the deaf)?', 'Reasonable adjustment logs for sensory impairments (e.g., flashing alarms).', false),
(51, 'responsive', 26, 'Planning for the future', 'Are ReSPECT (Recommended Summary Plan for Emergency Care and Treatment) forms completed and reviewed annually for all frail or elderly residents?', 'Annual ReSPECT forms completed for frail/elderly residents.', true),
(52, 'responsive', 26, 'Planning for the future', 'Are advance decisions to refuse treatment (ADRTs) securely stored in the front of the care plan and shared with the out-of-hours service?', 'ADRTs stored in front of care plans, shared with OOH service logs.', false),
-- WELL-LED (16 questions)
(53, 'well_led', 27, 'Shared direction and culture', 'Is the service''s statement of purpose reviewed annually, signed by the Registered Manager, and provided to all new service users?', 'Annual Statement of Purpose signed by RM, provided to new users.', true),
(54, 'well_led', 27, 'Shared direction and culture', 'Are the organization''s core values displayed in the main reception and referenced in staff recruitment interview scoring matrices?', 'Core values displayed in reception, referenced in interview matrices.', false),
(55, 'well_led', 28, 'Capable, compassionate and inclusive leaders', 'Does the Registered Manager hold an active, valid Level 5 Diploma in Leadership for Health and Social Care?', 'Registered Manager''s valid Level 5 Diploma certificate.', false),
(56, 'well_led', 28, 'Capable, compassionate and inclusive leaders', 'Are leadership team members required to complete annual ''compassionate leadership'' or ''inclusive management'' training?', 'Leadership training records for compassionate/inclusive management.', false),
(57, 'well_led', 29, 'Freedom to speak up', 'Is there an independent, external whistleblowing hotline available to staff, with the number displayed in the staff room and on payslips?', 'External whistleblowing hotline details on payslips and notice boards.', true),
(58, 'well_led', 29, 'Freedom to speak up', 'Are "freedom to speak up" champions appointed for every shift, with their names and photos displayed on the staff noticeboard?', 'Freedom to Speak Up champion list with photos on staff notice board.', false),
(59, 'well_led', 30, 'Workforce equality, diversity and inclusion', 'Is workforce demographic data collected and analyzed annually to identify any pay gaps or promotion disparities among protected groups?', 'Annual workforce demographic and pay gap analysis reports.', false),
(60, 'well_led', 30, 'Workforce equality, diversity and inclusion', 'Do all staff have access to an annual cultural or religious calendar, with shift rotas adjusted to accommodate major religious observances where possible?', 'Cultural/religious calendar and shift rota adjustments.', false),
(61, 'well_led', 31, 'Governance, management and sustainability', 'Is a comprehensive mock CQC inspection conducted bi-annually by an external consultant or independent internal auditor?', 'Bi-annual mock CQC inspection reports by external consultants.', false),
(62, 'well_led', 31, 'Governance, management and sustainability', 'Are financial viability reports reviewed quarterly by the board to ensure the service can sustain high-quality care without budget cuts?', 'Quarterly financial viability reports reviewed by the board.', false),
(63, 'well_led', 32, 'Partnerships and communities', 'Are formal partnership agreements in place with local hospitals, pharmacies, and community health teams, reviewed annually?', 'Formal partnership agreements with local health teams (annual review).', false),
(64, 'well_led', 32, 'Partnerships and communities', 'Does the service host or participate in at least one community integration event per quarter (e.g., opening the cafe to the public)?', 'Records of quarterly community integration events.', false),
(65, 'well_led', 33, 'Learning, improvement and innovation', 'Are lessons learned from external serious incident alerts (e.g., RASCI alerts) discussed in team meetings and signed off by all staff?', 'Team meeting minutes discussing external serious incident alerts.', false),
(66, 'well_led', 33, 'Learning, improvement and innovation', 'Is there a dedicated, ring-fenced annual budget specifically allocated for staff training and service innovation projects?', 'Annual budget allocation documents for training and innovation.', false),
(67, 'well_led', 34, 'Environmental sustainability, sustainable development', 'Is there a documented environmental policy that includes targets for reducing single-use plastics and food waste?', 'Documented environmental policy with single-use plastic targets.', false),
(68, 'well_led', 34, 'Environmental sustainability, sustainable development', 'Are energy consumption (gas/electricity) and water usage meters monitored monthly to identify leaks or excessive usage?', 'Monthly energy and water meter monitoring logs.', false)
on conflict (id) do update set
  domain = excluded.domain,
  statement_no = excluded.statement_no,
  statement = excluded.statement,
  question = excluded.question,
  evidence_hint = excluded.evidence_hint,
  priority = excluded.priority;
